### PR TITLE
fix typo in ZeroMQ

### PR DESCRIPTION
**Pull request by smanders**
* also sync up the README with the zeromq project file so the cmake-generated README will match
* fixes issue https://github.com/distributePro/ovsrpro/issues/27

### CODE REVIEW

**Comment by smanders** [comment]
is @tjflexmaster the same as @tgledhill? I'm attempting to have TJ review the changes to the ZeroMQ project file he introduced...

**Comment by brobeson** [comment]
> is @tjflexmaster the same as @tgledhill?

Yep.

**Review by brobeson — APPROVED** [review]
Thank you.

**Review by tjflexmaster — APPROVED** [review]

**Review by bnhhughes — APPROVED** [review]

**Review by swflb — APPROVED** [review]

**Comment by swflb** [comment]
sorry I was out most of the last two days dealing with sick minions

**Comment by smanders** [comment]
Resolves #27 
will this automatically close the issue? or did I need special words before this pull was merged?

**Comment by brobeson** [comment]
@smanders "fixes" should have worked. I suspect the word "issue" prevented it from closing the issue automatically.

**Pull request merged**
