### PR TITLE
replace obsolete xpRepo with xpCloneProject

### LINKED ISSUE #35: xpRepo is obsolete
the `cmake -DXP_STEP=mkpatch /path/to/src` step fails...

`xpRepo()` is obsolete (removed from externpro) -- should be replaced with `xpCloneProject()`

### PR DESCRIPTION
**Pull request by smanders**
fixes https://github.com/distributePro/ovsrpro/issues/35

### CODE REVIEW

**Review by brobeson — APPROVED** [review]
@smanders Github is telling me that you added the reviewers. Did you do it when you created the pull request, or did you let Github do it automatically? Just trying to get a sense of if Github is adding code owners on your behalf.

**Comment by brobeson** [comment]
@smanders Nevermind. I see the difference in the time line messages about adding reviewers.

**Review by swflb — APPROVED** [review]
thanks

**Comment by swflb** [comment]
I think @bnhhughes will not have issues and he won't see this for a few hours anyway.

**Review by bnhhughes — COMMENTED** [review]
Not that it matters now but I approve...

**Comment by smanders** [comment]
@brobeson yes - I'm also playing with the reviewers and getting a sense of what it does... I added @brobeson and @swflb manually as I was in the process of creating the pull (clicked on "Reviewers"), then when I created the pull it automatically added @bnhhughes -- pretty cool

**Pull request merged**
