### PR TITLE
Add support for generating RPM package

### PR DESCRIPTION
**Pull request by bnhhughes**
- Update to a newer version of externpro (16.01.1)  - allows to specify package type other than STGZ
- Some cleanup in the GLEW package, removing unnecessary Makefile patch and instead specifying paths on the make command line
- Remove Kerberos from Linux build (can cause conflicts with system installed kerberos libraries)
- Update Findexternpro (and Findovsrpro) files to match the ones the new version of externpro generates
- Add new cmake variable to specify different package generator
- Add post install/uninstall scripts to set/remove paths to libraries when installing via RPM
- Update README

### CODE REVIEW

**Comment by bnhhughes** [comment]
@incessantier - Here's the latest changes (removing kerberos for linux builds, rpm installer support, externpro 16.01.1, etc.)

**Comment by twaters** [comment]
@bnhhughes it looks pretty good to me.  I don't see anything I'm worried about.  Thanks!

**Comment by twaters** [comment]
#approved

**Comment by swflb** [comment]
@bnhhughes I am good allowing this in.

**Pull request merged**
